### PR TITLE
Add uk_ua.json

### PR DESCRIPTION
**Pull request by mewnn**
Full ukrainian translation of the mod. The book's texts are matched to the given space in the book.

### CODE REVIEW

**Comment by SammySemicolon** [comment]
I appreciate it, I will merge the PR. Do note though, the mod just received a pretty major update, so a lot of this might be outdated :( 
Sorry!

**Comment by mewnn** [comment]
> I appreciate it, I will merge the PR. Do note though, the mod just received a pretty major update, so a lot of this might be outdated :(
> Sorry!

It’s ok, I’ll just translate missing parts :)

**Comment by SammySemicolon** [comment]
All good :) Literally the entire book was rewritten though so I feel so bad TwT

**Comment by mewnn** [comment]
> All good :) Literally the entire book was rewritten though so I feel so bad TwT

oh god.. well, I’ll translate it… again.. T^T

**Pull request merged**
